import type { Metadata } from 'next'
import { Toaster, toast } from 'sonner'
import './globals.css'

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <head>
                <link rel="preconnect" href="https://fonts.googleapis.com"/>
                <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
                <link href="https://fonts.googleapis.com/css2?family=Arvo:ital,wght@0,400;0,700;1,400;1,700&family=Black+Ops+One&family=Lato:ital,wght@0,300;0,400;0,700;1,300;1,400;1,700&display=swap" rel="stylesheet"/>
            </head>
            <body className="min-h-full pb-10 bg-stone-200">
                {children}

                <Toaster
                    toastOptions={{
                        classNames: {
                            error: 'bg-red-400',
                            success: 'text-green-400',
                            warning: 'text-yellow-400',
                            info: 'bg-blue-400',
                        }
                    }}
                />
            </body>
        </html>
    )
}